export default defineNuxtConfig({
  devtools: { enabled: true },
  compatibilityDate: '2024-11-11',
modules: [
    '@nuxtjs/seo',
    '@nuxtjs/tailwindcss',
    '@nuxtjs/strapi',
    '@nuxt/content',
    '@nuxtjs/fontawesome',
    '@nuxtjs/i18n',
    '@nuxtjs/sitemap',
    '@nuxtjs/robots',
    '@nuxtjs/web-vitals',
    '@nuxtjs/turnstile',
    '@nuxtjs/partytown',
    '@nuxtjs/critters',
    '@nuxt/image',
    '@nuxtjs/device',
    '@nuxtjs/google-fonts',
],
  plugins: ['~/plugins/suppress-router-warn.js'],
  '~/plugins/fontawesome.js',
  css: ['~/assets/css/tailwind.css'],
  build: {
    transpile: ['@fortawesome/vue-fontawesome'],
    '@fortawesome/vue-fontawesome',
  },
    component: 'FontAwesomeIcon',
    suffix: true,
  },
  runtimeConfig: {
    public: {
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL || 'https://example.com',
      siteName: 'Ixome AI',
      siteDescription: 'AI-powered smart home support',
      language: 'en-US',
    },
  },
  app: {
  site: {
    url: 'https://ixome.ai',
    name: 'Ixome AI',
    description: 'AI-powered smart home support',
    defaultLocale: 'en',
  },
    head: {
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1',
    },
  },
});
