export default defineNuxtConfig({
  devtools: { enabled: true },
  compatibilityDate: '2024-11-11',
  extends: ['nuxt-seo-kit'],
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxtjs/strapi',
    '@nuxt/content',
    '@nuxtjs/fontawesome',
    '@nuxtjs/color-mode',
    '@nuxtjs/eslint-module',
    '@nuxtjs/stylelint-module',
    '@nuxtjs/prismic',
    '@nuxtjs/seo',
    '@nuxtjs/i18n',
    '@nuxtjs/sitemap',
    '@nuxtjs/robots',
    '@nuxtjs/web-vitals',
    '@nuxtjs/turnstile',
    '@nuxtjs/partytown',
    '@nuxtjs/critters',
    '@nuxtjs/image',
    '@nuxtjs/device',
    '@nuxtjs/google-fonts',
    '@nuxtjs/tailwindcss',
    '@nuxtjs/studio',
    '@nuxtjs/supabase',
    '@nuxtjs/apollo',
    '@nuxtjs/algolia',
    '@nuxtjs/plausible',
    '@nuxtjs/sanity',
    '@nuxtjs/storybook',
    '@nuxtjs/ui',
    '@nuxtjs/vueuse',
    '@nuxtjs/security',
    '@nuxtjs/leaflet',
    '@nuxtjs/mdc',
    '@nuxtjs/ionic',
    '@nuxtjs/pwa',
    '@nuxtjs/gtm',
    '@nuxtjs/html-validator',
    '@nuxtjs/swiper',
    '@nuxtjs/toast',
    '@nuxtjs/cookieconsent',
    '@nuxtjs/fontaine',
    '@nuxtjs/apollo',
    '@nuxtjs/seo-kit',
  ],
  plugins: ['~/plugins/suppress-router-warn.js'],
  css: ['~/assets/css/tailwind.css'],
  build: {
    transpile: ['@fortawesome/vue-fontawesome'],
  },
  fontawesome: {
    icons: {
      solid: ['faServer', 'faCode', 'faUsers'],
    },
    component: 'FontAwesomeIcon',
    suffix: true,
  },
  runtimeConfig: {
    public: {
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL || 'https://example.com',
      siteName: 'Ixome AI',
      siteDescription: 'AI-powered smart home support',
      language: 'en-US',
    },
  },
  app: {
    head: {
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1',
    },
  },
});
